#!/usr/bin/env python3
# semoe_transcode.py -- 세모이 libhangul-body XML(<map>/<combination>, 첫가끝) -> V2 확장 XML
#   (<jaso-map>/<combine>, type=sebeol-chord, engine=v2, yet=true, loose-order).
# 순수 데이터 재직렬화: 코드포인트(첫가끝 U+11xx) 그대로, 역할은 첫가끝 범위로 분류, 포맷만 변환.
# 엔진 무변경(jaso_chord_compose_sebeol + yet 커널 + 결합표 = 기존 데이터구동 구조로 조립).
import re, sys, html

# 첫가끝(Hangul Jamo) 범위 -> 역할
def role(cp):
    if 0x1100 <= cp <= 0x115F: return 'onset'   # 초성(모던+옛+filler)
    if 0x1160 <= cp <= 0x11A7: return 'vowel'   # 중성(filler+모던+옛, 쌍아래아 11A2 포함)
    if 0x11A8 <= cp <= 0x11FF: return 'coda'    # 종성(모던+옛)
    return None  # 비-자모(ASCII/기호)

def table(cp):
    r = role(cp)
    return {'onset':'cho','vowel':'jung','coda':'jong'}.get(r)

def parse_items(xml, tag_open, tag_close, attrs):
    # tag_open..tag_close 섹션 안의 <item .../> 들에서 attrs 추출
    sec = xml[xml.find(tag_open):]
    sec = sec[:sec.find(tag_close)] if tag_close in sec else sec
    out = []
    for m in re.finditer(r'<item\b([^/>]*)/?>', sec):
        a = m.group(1)
        vals = {}
        for k in attrs:
            mm = re.search(k + r'\s*=\s*"([^"]+)"', a)
            if mm: vals[k] = int(mm.group(1), 0)
        if all(k in vals for k in attrs):
            out.append(vals)
    return out

def is_old_jamo(cp):
    # 한글 자모 블록(U+1100~U+11FF) 중 모던 범위(초 1100-1112·중 1161-1175·종 11A8-11C2) 밖 = 옛자모
    if not (0x1100 <= cp <= 0x11FF): return False
    if 0x1100 <= cp <= 0x1112: return False
    if 0x1161 <= cp <= 0x1175: return False
    if 0x11A8 <= cp <= 0x11C2: return False
    return True

def transcode(src_path, kb_id, name_ko, out_path, name_override=None):
    import os
    xml = open(src_path, encoding='utf-8').read()
    # name: override > 소스 <name> > id
    mn = re.search(r'<name(?:\s[^>]*)?>([^<]+)</name>', xml)
    src_name = name_override or (mn.group(1).strip() if mn else name_ko)
    # abbrev capability flag (소스 <flags abbrev="true">) 보존
    has_abbrev = bool(re.search(r'<flags[^>]*\babbrev\s*=\s*"true"', xml))
    yet_needed = False
    map_items = parse_items(xml, '<map', '</map>', ['key', 'value'])
    keys = []
    n_jamo = n_old = n_lit = 0
    for it in map_items:
        k, v = it['key'], it['value']
        r = role(v)
        if r:
            keys.append((k, r, v))
            n_jamo += 1
            if is_old_jamo(v): n_old += 1; yet_needed = True
        elif v != k and v >= 0x3000:
            keys.append((k, 'literal', v)); n_lit += 1   # 기호(SX) — 식별 literal
        # else: ASCII 패스스루 identity -> 생략(V2 미매핑 통과)
    # <combination> — 인라인 또는 <include file=...> (안마태)
    comb_xml = xml
    inc = re.search(r'<include\s+file\s*=\s*"([^"]+)"', xml)
    if inc and '<combination' not in xml:
        incpath = os.path.join(os.path.dirname(src_path), inc.group(1))
        comb_xml = open(incpath, encoding='utf-8').read()
    comb = parse_items(comb_xml, '<combination', '</combination>', ['first', 'second', 'result'])
    # yet 도 결합표(first/second/result)에서 옛자모 나오면 true
    for it in comb:
        if is_old_jamo(it['first']) or is_old_jamo(it['second']) or is_old_jamo(it['result']):
            yet_needed = True; break
    tabs = {'cho': [], 'jung': [], 'jong': []}
    for it in comb:
        t = table(it['result'])
        if t: tabs[t].append((it['first'], it['second'], it['result']))

    keys.sort(key=lambda x: x[0])
    L = []
    L.append('<?xml version="1.0" encoding="UTF-8"?>')
    L.append('<!-- %s — 세모이(세벌식 모아치기) V2 확장 XML (KEYBOARD_FORMAT.md §13).' % src_name)
    L.append('     GENERATED by semoe_transcode from libhangul-body %s.xml — 첫가끝 그대로(코드포인트 변환 0),' % kb_id)
    L.append('     역할은 첫가끝 범위로 분류, 포맷만 V2. 손편집 금지 — 소스 변경 시 재생성.')
    L.append('     런타임: V2 로더가 engine="v2"를 보고 V2 clean 커널로 구동(chord=jaso_chord_compose_sebeol,')
    L.append('     옛한글=yet conjoining). 약어/후보는 별도 데이터(.dic/.tsv). 본가: Sinseiki Semo-e (CC BY-SA). -->')
    L.append('<hangul-keyboard id="%s" type="sebeol-chord">' % kb_id)
    L.append('  <name>%s</name>' % html.escape(src_name))
    L.append('  <flags loose-order="true"%s/>' % (' abbrev="true"' if has_abbrev else ''))
    L.append('  <jaso engine="v2" role-flip="none" right-oua="false" yet="%s"/>' % ('true' if yet_needed else 'false'))
    L.append('  <jaso-map>')
    for k, r, v in keys:
        L.append('    <key code="0x%02X" kind="%s" a="0x%X" b="0x0"/>' % (k, r, v))
    L.append('  </jaso-map>')
    for t in ('cho', 'jung', 'jong'):
        L.append('  <combine table="%s">' % t)
        for f, s, res in tabs[t]:
            L.append('    <item have="0x%X" add="0x%X" result="0x%X"/>' % (f, s, res))
        L.append('  </combine>')
    L.append('</hangul-keyboard>')
    open(out_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
    print('OK %-18s -> %s  (jamo=%d old=%d lit=%d yet=%s | cho=%d jung=%d jong=%d)'
          % (kb_id, out_path, n_jamo, n_old, n_lit, yet_needed,
             len(tabs['cho']), len(tabs['jung']), len(tabs['jong'])))

if __name__ == '__main__':
    src, kid, out = sys.argv[1], sys.argv[2], sys.argv[3]
    nm = sys.argv[4] if len(sys.argv) > 4 else None
    transcode(src, kid, kid, out, nm)
